/* ============================================================
   BazaarCo — Catalog data (realistic Nepali products, Rs. prices)
   ============================================================ */
export const CATEGORIES = [
  {
    id: "electronics",
    en: "Electronics",
    icon: "phone",
    tint: "slate",
    img: "https://picsum.photos/seed/cat-electronics/300/300",
  },
  {
    id: "home-appliances",
    en: "Home Appliances",
    icon: "home",
    tint: "blue",
    img: "https://picsum.photos/seed/cat-home-appliances/300/300",
  },
  {
    id: "fashion",
    en: "Fashion",
    icon: "shirt",
    tint: "red",
    img: "https://picsum.photos/seed/cat-fashion/300/300",
  },
  {
    id: "health-beauty",
    en: "Health & Beauty",
    icon: "lipstick",
    tint: "purple",
    img: "https://picsum.photos/seed/cat-health-beauty/300/300",
  },
  {
    id: "groceries-essentials",
    en: "Groceries & Essentials",
    icon: "basket",
    tint: "green",
    img: "https://picsum.photos/seed/cat-groceries-essentials/300/300",
  },
  {
    id: "home-living",
    en: "Home & Living",
    icon: "home",
    tint: "teal",
    img: "https://picsum.photos/seed/cat-home-living/300/300",
  },
  {
    id: "mother-baby-kids",
    en: "Mother, Baby & Kids",
    icon: "pacifier",
    tint: "purple",
    img: "https://picsum.photos/seed/cat-mother-baby-kids/300/300",
  },
  {
    id: "sports-outdoors",
    en: "Sports & Outdoors",
    icon: "football",
    tint: "teal",
    img: "https://picsum.photos/seed/cat-sports-outdoors/300/300",
  },
  {
    id: "automotive",
    en: "Automotive",
    icon: "truck",
    tint: "slate",
    img: "https://picsum.photos/seed/cat-automotive/300/300",
  },
  {
    id: "books-stationery",
    en: "Books & Stationery",
    icon: "book",
    tint: "gold",
    img: "https://picsum.photos/seed/cat-books-stationery/300/300",
  },
  {
    id: "musical-instruments",
    en: "Musical Instruments",
    icon: "headphones",
    tint: "saffron",
    img: "https://picsum.photos/seed/cat-musical-instruments/300/300",
  },
  {
    id: "pet-supplies",
    en: "Pet Supplies",
    icon: "leaf",
    tint: "green",
    img: "https://picsum.photos/seed/cat-pet-supplies/300/300",
  },
  {
    id: "crafts-heritage",
    en: "Crafts & Heritage",
    icon: "temple",
    tint: "saffron",
    img: "https://picsum.photos/seed/cat-crafts-heritage/300/300",
  },
  {
    id: "digital-goods-services",
    en: "Digital Goods & Services",
    icon: "file",
    tint: "blue",
    img: "https://picsum.photos/seed/cat-digital-goods-services/300/300",
  },
  {
    id: "tools-home-improvement",
    en: "Tools & Home Improvement",
    icon: "settings",
    tint: "gold",
    img: "https://picsum.photos/seed/cat-tools-home-improvement/300/300",
  },
  {
    id: "medical-office-supplies",
    en: "Medical & Office Supplies",
    icon: "filePlus",
    tint: "slate",
    img: "https://picsum.photos/seed/cat-medical-office-supplies/300/300",
  },
];

/* ============================================================
   Category-specific listing attributes (seller Add-product)
   Field shape: { k:key, en, ne, t:type, req?:mandatory,
                  o?:options[], u?:unit, help? }
   types: "select" | "multi" | "text" | "num" | "toggle" | "date"
   `req` fields drive the "missing detail" warning in Add-product.
   Options stay English (sizes/standards/proper nouns); labels bilingual.
   ============================================================ */
export const ATTR_CATEGORIES = [
  { id: "electronics", en: "Electronics", icon: "phone" },
  { id: "home-appliances", en: "Home Appliances", icon: "home" },
  { id: "fashion", en: "Fashion", icon: "shirt" },
  { id: "health-beauty", en: "Health & Beauty", icon: "lipstick" },
  { id: "groceries-essentials", en: "Groceries & Essentials", icon: "basket" },
  { id: "home-living", en: "Home & Living", icon: "home" },
  { id: "mother-baby-kids", en: "Mother, Baby & Kids", icon: "pacifier" },
  { id: "sports-outdoors", en: "Sports & Outdoors", icon: "football" },
  { id: "automotive", en: "Automotive", icon: "truck" },
  { id: "books-stationery", en: "Books & Stationery", icon: "book" },
  { id: "musical-instruments", en: "Musical Instruments", icon: "headphones" },
  { id: "pet-supplies", en: "Pet Supplies", icon: "leaf" },
  { id: "crafts-heritage", en: "Crafts & Heritage", icon: "temple" },
  { id: "digital-goods-services", en: "Digital Goods & Services", icon: "file" },
  { id: "tools-home-improvement", en: "Tools & Home Improvement", icon: "settings" },
  { id: "medical-office-supplies", en: "Medical & Office Supplies", icon: "filePlus" },
];

export const LEGACY_CATEGORY_ATTRIBUTES = {
  fashion: [
    {
      k: "department",
      en: "For whom",
      t: "select",
      req: true,
      o: ["Men", "Women", "Kids", "Unisex"],
    },
    {
      k: "size",
      en: "Size",
      t: "multi",
      req: true,
      o: ["XS", "S", "M", "L", "XL", "XXL", "Free size"],
    },
    {
      k: "sizeFormat",
      en: "Size standard",
      t: "select",
      o: ["IND", "UK", "US", "EU"],
    },
    {
      k: "color",
      en: "Colour",
      t: "multi",
      req: true,
      o: [
        "Black",
        "White",
        "Red",
        "Blue",
        "Green",
        "Maroon",
        "Beige",
        "Grey",
        "Yellow",
        "Pink",
        "Multi",
      ],
    },
    {
      k: "fabric",
      en: "Fabric",
      t: "select",
      req: true,
      o: ["Cotton", "Silk", "Pashmina", "Wool", "Polyester", "Denim", "Linen", "Hemp/Allo"],
    },
    { k: "fit", en: "Fit", t: "select", o: ["Slim", "Regular", "Relaxed", "Oversized"] },
    {
      k: "sleeve",
      en: "Sleeve",
      t: "select",
      o: ["Short", "Long", "Sleeveless", "3/4 sleeve"],
    },
    {
      k: "pattern",
      en: "Pattern",
      t: "select",
      o: ["Solid", "Striped", "Floral", "Checked", "Printed"],
    },
    {
      k: "occasion",
      en: "Occasion",
      t: "select",
      o: ["Casual", "Formal", "Party", "Office", "Festive"],
    },
    {
      k: "care",
      en: "Wash care",
      t: "select",
      o: ["Machine wash", "Hand wash", "Dry clean"],
    },
    {
      k: "season",
      en: "Season",
      t: "select",
      o: ["Summer", "Winter", "Spring", "Autumn", "All season"],
    },
  ],
  footwear: [
    {
      k: "department",
      en: "For whom",
      t: "select",
      req: true,
      o: ["Men", "Women", "Kids", "Unisex"],
    },
    {
      k: "size",
      en: "Size",
      t: "multi",
      req: true,
      o: [
        "UK 5",
        "UK 6",
        "UK 7",
        "UK 8",
        "UK 9",
        "UK 10",
        "UK 11",
        "EU 40",
        "EU 41",
        "EU 42",
        "EU 43",
        "EU 44",
      ],
    },
    {
      k: "color",
      en: "Colour",
      t: "multi",
      req: true,
      o: ["Black", "White", "Brown", "Tan", "Blue", "Grey", "Red", "Multi"],
    },
    {
      k: "upper",
      en: "Upper material",
      t: "select",
      req: true,
      o: ["Leather", "Suede", "Mesh", "Canvas", "Synthetic"],
    },
    {
      k: "sole",
      en: "Sole material",
      t: "select",
      o: ["Rubber", "EVA", "Leather", "PU", "Synthetic"],
    },
    {
      k: "closure",
      en: "Closure",
      t: "select",
      o: ["Lace-up", "Slip-on", "Buckle", "Zipper", "Velcro"],
    },
    {
      k: "heel",
      en: "Heel height",
      t: "select",
      o: ["Flat (0–2cm)", "Low (2–5cm)", "Medium (5–7cm)", "High (7cm+)"],
    },
    {
      k: "occasion",
      en: "Occasion",
      t: "select",
      o: ["Casual", "Sports", "Formal", "Hiking", "Party"],
    },
    {
      k: "water",
      en: "Water resistance",
      t: "select",
      o: ["Waterproof", "Water-resistant", "Not waterproof"],
    },
  ],
  "health-beauty": [
    {
      k: "type",
      en: "Product type",
      t: "select",
      req: true,
      o: ["Skincare", "Makeup", "Hair care", "Fragrance", "Personal care"],
    },
    {
      k: "volume",
      en: "Net volume / weight",
      t: "text",
      req: true,
      u: "ml / g",
      help: "Needed for delivery cost.",
    },
    {
      k: "expiry",
      en: "Expiry / best before",
      t: "date",
      req: true,
      help: "Required for anything applied to skin.",
    },
    {
      k: "skinType",
      en: "Skin type",
      t: "select",
      o: ["Normal", "Dry", "Oily", "Combination", "Sensitive", "All"],
    },
    {
      k: "form",
      en: "Form",
      t: "select",
      o: ["Liquid", "Cream", "Powder", "Gel", "Stick", "Spray"],
    },
    { k: "spf", en: "SPF", t: "text", help: "Leave blank if none." },
    {
      k: "ingredients",
      en: "Key ingredients",
      t: "text",
      req: true,
      help: "List main ingredients — buyers with allergies check this.",
    },
    { k: "crueltyFree", en: "Cruelty-free / vegan", t: "toggle" },
    {
      k: "benefits",
      en: "Benefits",
      t: "multi",
      o: ["Hydrating", "Anti-aging", "Brightening", "Oil-control", "Soothing"],
    },
  ],
  electronics: [
    { k: "brand", en: "Brand & model", t: "text", req: true },
    {
      k: "color",
      en: "Colour",
      t: "select",
      o: ["Black", "White", "Silver", "Blue", "Gold", "Grey"],
    },
    {
      k: "ram",
      en: "RAM",
      t: "select",
      o: ["2GB", "4GB", "6GB", "8GB", "12GB", "16GB", "N/A"],
    },
    {
      k: "storage",
      en: "Storage",
      t: "select",
      o: ["32GB", "64GB", "128GB", "256GB", "512GB", "1TB", "N/A"],
    },
    {
      k: "display",
      en: "Display size",
      t: "text",
      help: "e.g. 6.5 inch AMOLED",
    },
    {
      k: "os",
      en: "Operating system",
      t: "text",
      help: "e.g. Android 14, iOS 18",
    },
    { k: "battery", en: "Battery", t: "text", u: "mAh" },
    {
      k: "connectivity",
      en: "Connectivity",
      t: "multi",
      o: ["5G", "4G", "Wi-Fi", "Bluetooth", "NFC"],
    },
    {
      k: "warranty",
      en: "Warranty",
      t: "select",
      req: true,
      o: ["No warranty", "3 months", "6 months", "1 year", "2 years"],
      help: "Big trust signal — buyers fear fakes.",
    },
    {
      k: "inBox",
      en: "What's in the box",
      t: "text",
      help: "e.g. Charger, cable, earphones",
    },
  ],
  accessories: [
    {
      k: "type",
      en: "Type",
      t: "select",
      req: true,
      o: ["Watch", "Bag", "Sunglasses", "Belt", "Hat", "Jewellery", "Scarf"],
    },
    {
      k: "material",
      en: "Main material",
      t: "select",
      req: true,
      o: ["Leather", "Metal", "Plastic", "Acetate", "Fabric", "Wood"],
    },
    {
      k: "color",
      en: "Colour",
      t: "multi",
      o: ["Black", "Brown", "Gold", "Silver", "Tan", "Multi"],
    },
    { k: "dimensions", en: "Size (L×W×H)", t: "text", help: "For bags & boxes." },
    {
      k: "movement",
      en: "Watch movement",
      t: "select",
      o: ["Quartz", "Automatic", "Mechanical", "Digital", "N/A"],
    },
    {
      k: "uv",
      en: "UV protection",
      t: "select",
      o: ["UV400", "Polarised", "Anti-glare", "None", "N/A"],
    },
    { k: "adjustable", en: "Adjustable", t: "toggle" },
  ],
  "home-living": [
    {
      k: "type",
      en: "Product type",
      t: "select",
      req: true,
      o: ["Cookware", "Bakeware", "Dinnerware", "Storage", "Cleaning", "Decor"],
    },
    {
      k: "material",
      en: "Material",
      t: "select",
      req: true,
      o: [
        "Stainless steel",
        "Cast iron",
        "Glass",
        "Ceramic",
        "Plastic",
        "Silicone",
        "Wood",
        "Brass",
        "Copper",
      ],
    },
    { k: "dimensions", en: "Size (L×W×H)", t: "text" },
    { k: "capacity", en: "Capacity", t: "text", u: "litre / ml" },
    {
      k: "color",
      en: "Colour",
      t: "select",
      o: ["Silver", "Black", "White", "Gold", "Multi"],
    },
    {
      k: "care",
      en: "Care",
      t: "multi",
      o: ["Dishwasher safe", "Hand wash", "Microwave safe", "Oven safe"],
    },
    {
      k: "compat",
      en: "Works with (cookware)",
      t: "multi",
      o: ["Gas", "Induction", "Ceramic", "Halogen"],
    },
    { k: "setPieces", en: "Pieces in set", t: "num" },
  ],
  furniture: [
    {
      k: "room",
      en: "Room",
      t: "select",
      req: true,
      o: ["Living room", "Bedroom", "Dining", "Office", "Outdoor"],
    },
    {
      k: "type",
      en: "Type",
      t: "select",
      req: true,
      o: ["Sofa", "Chair", "Table", "Bed", "Cabinet", "Shelf"],
    },
    {
      k: "material",
      en: "Main material",
      t: "select",
      req: true,
      o: ["Solid wood", "Engineered wood", "Metal", "Glass", "Rattan", "Fabric"],
    },
    { k: "dimensions", en: "Size (W×D×H)", t: "text", req: true, u: "cm" },
    { k: "color", en: "Colour / finish", t: "text" },
    { k: "assembly", en: "Needs assembly", t: "toggle" },
    {
      k: "wallFix",
      en: "Must fix to wall",
      t: "toggle",
      help: "Show for tall cabinets/shelves — safety.",
    },
    { k: "weightCap", en: "Weight it can hold", t: "text", u: "kg" },
  ],
  "groceries-essentials": [
    {
      k: "foodType",
      en: "Food type",
      t: "select",
      req: true,
      o: ["Staples", "Snacks", "Beverages", "Dairy", "Spices", "Oil & ghee"],
    },
    { k: "brand", en: "Brand", t: "text" },
    {
      k: "weight",
      en: "Net weight / volume",
      t: "text",
      req: true,
      u: "kg / g / L / ml",
    },
    { k: "mfgDate", en: "Made on", t: "date", req: true },
    { k: "expiry", en: "Best before / expiry", t: "date", req: true },
    {
      k: "storage",
      en: "How to store",
      t: "select",
      o: ["Cool & dry place", "Refrigerate", "Refrigerate after opening"],
    },
    {
      k: "ingredients",
      en: "Ingredients",
      t: "text",
      req: true,
      help: "Mark major allergens.",
    },
    {
      k: "diet",
      en: "Dietary",
      t: "multi",
      o: ["Organic", "Gluten-free", "Sugar-free", "Vegan"],
    },
    {
      k: "origin",
      en: "Country of origin",
      t: "text",
      help: "Needed for imported goods.",
    },
    {
      k: "license",
      en: "Food licence no.",
      t: "text",
      help: "Required to sell packaged food in Nepal.",
    },
  ],
  "books-stationery": [
    {
      k: "type",
      en: "Type",
      t: "select",
      req: true,
      o: ["Book", "Notebook", "Pen", "Art supply", "Office supply"],
    },
    { k: "title", en: "Title", t: "text", help: "For books." },
    { k: "author", en: "Author", t: "text" },
    { k: "publisher", en: "Publisher", t: "text" },
    {
      k: "language",
      en: "Language",
      t: "select",
      o: ["Nepali", "English", "Hindi", "Maithili", "Newari", "Other"],
    },
    {
      k: "isbn",
      en: "ISBN",
      t: "text",
      help: "Required for books (10 or 13 digit).",
    },
    {
      k: "format",
      en: "Format",
      t: "select",
      o: ["Paperback", "Hardcover", "eBook", "Audiobook"],
    },
    { k: "pages", en: "Pages", t: "num" },
    {
      k: "genre",
      en: "Genre / subject",
      t: "select",
      o: ["Fiction", "Non-fiction", "Biography", "Academic", "Children's", "Cookbook"],
    },
  ],
  "crafts-heritage": [
    {
      k: "craft",
      en: "Craft type",
      t: "select",
      req: true,
      o: [
        "Pashmina / wool",
        "Lokta paper",
        "Pottery",
        "Wood carving",
        "Metal craft",
        "Thangka painting",
      ],
    },
    {
      k: "material",
      en: "Main material",
      t: "select",
      req: true,
      o: ["Wool", "Lokta fibre", "Clay", "Wood", "Brass", "Cotton"],
    },
    { k: "handmade", en: "Fully handmade", t: "toggle", req: true },
    {
      k: "method",
      en: "How it's made",
      t: "select",
      o: ["Hand-woven", "Hand-knotted", "Hand-carved", "Hand-painted", "Hand-thrown"],
    },
    {
      k: "community",
      en: "Made in (district)",
      t: "text",
      req: true,
      help: "e.g. Bhaktapur, Pokhara — buyers love local origin.",
    },
    {
      k: "story",
      en: "Artisan story",
      t: "text",
      help: "A line about the maker builds trust.",
    },
    { k: "dye", en: "Dye", t: "select", o: ["Natural dye", "Chemical dye"] },
    {
      k: "leadTime",
      en: "Days to make (custom)",
      t: "num",
      help: "For made-to-order items.",
    },
  ],
  "mother-baby-kids": [
    {
      k: "type",
      en: "Product type",
      t: "select",
      req: true,
      o: ["Diapers", "Feeding bottle", "Baby gear", "Clothing", "Toys", "Skincare"],
    },
    {
      k: "ageRange",
      en: "Baby age",
      t: "select",
      req: true,
      o: ["Newborn (0–3m)", "3–6m", "6–12m", "12–18m", "18–24m", "2–4 yr"],
    },
    {
      k: "material",
      en: "Material",
      t: "select",
      o: ["Cotton", "Silicone", "BPA-free plastic", "Wood", "Fabric"],
    },
    {
      k: "safetyCert",
      en: "Safety certificate",
      t: "text",
      req: true,
      help: "BIS / ISO / CE — required for child safety.",
    },
    { k: "bpaFree", en: "BPA-free", t: "toggle" },
    { k: "hypoallergenic", en: "Hypoallergenic", t: "toggle" },
    {
      k: "care",
      en: "Cleaning",
      t: "select",
      o: ["Machine wash gentle", "Sterilise", "Hand wash"],
    },
  ],
  "sports-outdoors": [
    {
      k: "activity",
      en: "Sport / activity",
      t: "select",
      req: true,
      o: ["Football", "Cricket", "Basketball", "Yoga", "Running", "Gym", "Swimming", "Trekking"],
    },
    {
      k: "type",
      en: "Type",
      t: "select",
      req: true,
      o: ["Ball", "Shoes", "Clothing", "Racket", "Mat", "Weights", "Bottle", "Tracker"],
    },
    {
      k: "gender",
      en: "For whom",
      t: "select",
      o: ["Men", "Women", "Unisex", "Kids"],
    },
    {
      k: "size",
      en: "Size / weight",
      t: "text",
      help: "e.g. 5kg dumbbell, Size 5 ball",
    },
    {
      k: "material",
      en: "Material",
      t: "select",
      o: ["Leather", "Synthetic", "Rubber", "Cotton", "Nylon", "Neoprene", "EVA"],
    },
    { k: "brand", en: "Brand", t: "text" },
    {
      k: "skill",
      en: "Skill level",
      t: "select",
      o: ["Beginner", "Intermediate", "Advanced", "Professional"],
    },
    {
      k: "warranty",
      en: "Warranty (equipment)",
      t: "select",
      o: ["No warranty", "6 months", "1 year", "2 years"],
    },
  ],
};

const COMMON_METADATA_FIELDS = [
  { k: "brand", en: "Brand", t: "text" },
  { k: "model", en: "Model / variant", t: "text" },
  { k: "material", en: "Material", t: "text" },
  {
    k: "color",
    en: "Colour",
    t: "multi",
    o: ["Black", "White", "Blue", "Red", "Green", "Grey", "Gold", "Silver", "Multi"],
    allowOther: true,
  },
  { k: "weight", en: "Weight", t: "text", u: "kg / g" },
  { k: "dimensions", en: "Dimensions", t: "text", u: "L x W x H" },
  { k: "origin", en: "Country / place of origin", t: "text" },
  { k: "warranty", en: "Warranty", t: "text" },
];

const CATEGORY_METADATA_FIELDS = {
  electronics: [
    {
      k: "productType",
      en: "Product type",
      t: "select",
      o: ["Mobile phone", "Laptop", "Tablet", "TV", "Camera", "Audio", "Accessory", "Other"],
    },
    { k: "batteryCapacity", en: "Battery capacity", t: "text", u: "mAh / Wh" },
    { k: "ram", en: "RAM", t: "text" },
    { k: "ramType", en: "RAM type", t: "text" },
    { k: "storage", en: "Storage", t: "text" },
    { k: "processor", en: "Processor", t: "text" },
    { k: "screenSize", en: "Screen size", t: "text", u: "inch" },
    { k: "operatingSystem", en: "Operating system", t: "text" },
    {
      k: "connectivity",
      en: "Connectivity",
      t: "multi",
      o: ["4G", "5G", "Wi-Fi", "Bluetooth", "NFC", "USB-C"],
      allowOther: true,
    },
  ],
  "home-appliances": [
    {
      k: "applianceType",
      en: "Appliance type",
      t: "select",
      o: [
        "Refrigerator",
        "Washing machine",
        "Microwave",
        "Rice cooker",
        "Fan",
        "Heater",
        "Mixer / grinder",
        "Other",
      ],
    },
    { k: "power", en: "Power", t: "text", u: "W" },
    { k: "capacity", en: "Capacity", t: "text", u: "L / kg" },
    { k: "energyRating", en: "Energy rating", t: "text" },
    { k: "voltage", en: "Voltage", t: "text" },
    { k: "installationRequired", en: "Installation required", t: "toggle" },
  ],
  fashion: [
    { k: "department", en: "For whom", t: "select", o: ["Men", "Women", "Kids", "Unisex"] },
    {
      k: "size",
      en: "Size",
      t: "multi",
      o: ["XS", "S", "M", "L", "XL", "XXL", "Free size"],
      allowOther: true,
    },
    { k: "fabric", en: "Fabric", t: "text" },
    { k: "fit", en: "Fit", t: "text" },
    { k: "pattern", en: "Pattern", t: "text" },
    { k: "care", en: "Care instructions", t: "text" },
  ],
  "health-beauty": [
    {
      k: "productType",
      en: "Product type",
      t: "select",
      o: ["Skincare", "Makeup", "Hair care", "Fragrance", "Personal care", "Supplement", "Other"],
    },
    { k: "netQuantity", en: "Net quantity", t: "text", u: "ml / g / pcs" },
    { k: "skinType", en: "Skin / hair type", t: "text" },
    { k: "ingredients", en: "Key ingredients", t: "text" },
    { k: "expiry", en: "Expiry / best before", t: "date" },
    { k: "certification", en: "Certification / approval", t: "text" },
  ],
  "groceries-essentials": [
    { k: "foodType", en: "Food / essential type", t: "text" },
    { k: "netWeight", en: "Net weight / volume", t: "text", u: "kg / g / L / ml" },
    { k: "ingredients", en: "Ingredients", t: "text" },
    { k: "mfgDate", en: "Manufactured / packed on", t: "date" },
    { k: "expiry", en: "Best before / expiry", t: "date" },
    { k: "storage", en: "Storage instructions", t: "text" },
    {
      k: "dietary",
      en: "Dietary tags",
      t: "multi",
      o: ["Organic", "Vegan", "Gluten-free", "Sugar-free"],
      allowOther: true,
    },
  ],
  "home-living": [
    { k: "productType", en: "Product type", t: "text" },
    { k: "room", en: "Room / use", t: "text" },
    { k: "capacity", en: "Capacity", t: "text" },
    { k: "setPieces", en: "Pieces in set", t: "num" },
    { k: "care", en: "Care instructions", t: "text" },
  ],
  "mother-baby-kids": [
    { k: "productType", en: "Product type", t: "text" },
    { k: "ageRange", en: "Age range", t: "text" },
    { k: "safetyCertification", en: "Safety certification", t: "text" },
    { k: "bpaFree", en: "BPA-free", t: "toggle" },
    { k: "hypoallergenic", en: "Hypoallergenic", t: "toggle" },
  ],
  "sports-outdoors": [
    { k: "activity", en: "Sport / activity", t: "text" },
    { k: "size", en: "Size", t: "text" },
    {
      k: "skillLevel",
      en: "Skill level",
      t: "select",
      o: ["Beginner", "Intermediate", "Advanced", "Professional"],
    },
    { k: "waterResistance", en: "Water resistance", t: "text" },
    { k: "loadCapacity", en: "Load capacity", t: "text", u: "kg" },
  ],
  automotive: [
    { k: "partType", en: "Part / accessory type", t: "text" },
    {
      k: "vehicleType",
      en: "Vehicle type",
      t: "select",
      o: ["Car", "Motorbike", "Scooter", "Truck", "Bus", "Other"],
    },
    { k: "compatibleModels", en: "Compatible models", t: "text" },
    { k: "yearRange", en: "Year range", t: "text" },
    { k: "partNumber", en: "Part number", t: "text" },
  ],
  "books-stationery": [
    {
      k: "productType",
      en: "Product type",
      t: "select",
      o: ["Book", "Notebook", "Pen", "Art supply", "Office supply", "Other"],
    },
    { k: "author", en: "Author", t: "text" },
    { k: "publisher", en: "Publisher", t: "text" },
    { k: "language", en: "Language", t: "text" },
    { k: "isbn", en: "ISBN", t: "text" },
    { k: "pages", en: "Pages", t: "num" },
  ],
  "musical-instruments": [
    { k: "instrumentType", en: "Instrument type", t: "text" },
    {
      k: "skillLevel",
      en: "Skill level",
      t: "select",
      o: ["Beginner", "Intermediate", "Professional"],
    },
    { k: "bodyMaterial", en: "Body material", t: "text" },
    { k: "stringCount", en: "String count", t: "num" },
    { k: "includedAccessories", en: "Included accessories", t: "text" },
  ],
  "pet-supplies": [
    {
      k: "petType",
      en: "Pet type",
      t: "select",
      o: ["Dog", "Cat", "Bird", "Fish", "Small pet", "Other"],
    },
    { k: "lifeStage", en: "Life stage", t: "select", o: ["Baby", "Adult", "Senior", "All ages"] },
    { k: "flavor", en: "Flavour / scent", t: "text" },
    { k: "netWeight", en: "Net weight / volume", t: "text" },
    { k: "ingredients", en: "Ingredients", t: "text" },
  ],
  "crafts-heritage": [
    { k: "craftType", en: "Craft type", t: "text" },
    { k: "artisan", en: "Artisan / maker", t: "text" },
    { k: "madeIn", en: "Made in", t: "text" },
    { k: "technique", en: "Technique", t: "text" },
    { k: "handmade", en: "Handmade", t: "toggle" },
  ],
  "digital-goods-services": [
    {
      k: "deliveryMethod",
      en: "Delivery method",
      t: "select",
      o: ["Email", "Download link", "Account activation", "Online service", "Other"],
    },
    { k: "licenseType", en: "License / access type", t: "text" },
    { k: "duration", en: "Duration", t: "text" },
    { k: "platform", en: "Platform", t: "text" },
    { k: "requirements", en: "Requirements", t: "text" },
  ],
  "tools-home-improvement": [
    { k: "toolType", en: "Tool / improvement type", t: "text" },
    {
      k: "powerSource",
      en: "Power source",
      t: "select",
      o: ["Manual", "Electric", "Battery", "Petrol", "Other"],
    },
    { k: "voltage", en: "Voltage", t: "text" },
    { k: "includedItems", en: "Included items", t: "text" },
    { k: "safetyRating", en: "Safety rating", t: "text" },
  ],
  "medical-office-supplies": [
    { k: "supplyType", en: "Supply type", t: "text" },
    { k: "quantity", en: "Quantity / pack size", t: "text" },
    { k: "sterile", en: "Sterile", t: "toggle" },
    { k: "expiry", en: "Expiry date", t: "date" },
    { k: "certification", en: "Certification / compliance", t: "text" },
  ],
};

export const CATEGORY_ATTRIBUTES = Object.fromEntries(
  CATEGORIES.map((category) => [
    category.id,
    [...COMMON_METADATA_FIELDS, ...(CATEGORY_METADATA_FIELDS[category.id] ?? [])],
  ]),
);

export const PROVINCES = [
  "Koshi",
  "Madhesh",
  "Bagmati",
  "Gandaki",
  "Lumbini",
  "Karnali",
  "Sudurpashchim",
];
