export const queryKeys = {
  auth: {
    me: ["auth", "me"] as const,
  },
  search: (params: Record<string, unknown>) => ["search", params] as const,
  catalog: {
    categories: ["catalog", "categories"] as const,
    sellers: ["catalog", "sellers"] as const,
    seller: (id: string) => ["catalog", "seller", id] as const,
    sellerReviews: (id: string) => ["catalog", "seller", id, "reviews"] as const,
    sellerProducts: (id: string) => ["catalog", "seller", id, "products"] as const,
    sellerTrust: (id: string) => ["catalog", "seller", id, "trust"] as const,
    products: (params?: object) => ["catalog", "products", params ?? {}] as const,
    topPicks: (days: number) => ["catalog", "top-picks", days] as const,
    newArrivals: ["catalog", "new-arrivals"] as const,
    product: (id: string) => ["catalog", "product", id] as const,
    productReviews: (id: string) => ["catalog", "product", id, "reviews"] as const,
    productProfile: (id: string) => ["catalog", "product", id, "profile"] as const,
    ratingDistribution: (id: string) => ["catalog", "product", id, "rating-distribution"] as const,
    reviewEligibility: (id: string) => ["catalog", "product", id, "review-eligibility"] as const,
    productQuestions: (id: string) => ["catalog", "product", id, "questions"] as const,
  },
  home: ["home"] as const,
  cart: {
    all: ["cart"] as const,
  },
  wishlist: {
    all: ["wishlist"] as const,
  },
  addresses: {
    all: ["addresses"] as const,
  },
  orders: {
    list: ["orders"] as const,
    detail: (id: string) => ["orders", id] as const,
  },
  tracking: (orderId: string) => ["tracking", orderId] as const,
  bargains: ["bargains"] as const,
  videos: {
    feed: (tab: string) => ["videos", "feed", tab] as const,
  },
  chat: {
    inbox: ["chat", "inbox"] as const,
    messages: (conversationId: string) => ["chat", "messages", conversationId] as const,
  },
  seller: {
    organization: ["seller", "organization"] as const,
    dashboard: (range: string) => ["seller", "dashboard", range] as const,
    inbox: (sellerId?: string | null) => ["seller", "inbox", sellerId ?? "none"] as const,
    inventory: ["seller", "inventory"] as const,
    bargains: ["seller", "bargains"] as const,
    reviews: ["seller", "reviews"] as const,
    chat: ["seller", "chat"] as const,
    promotions: ["seller", "promotions"] as const,
    videos: ["seller", "videos"] as const,
    analytics: ["seller", "analytics"] as const,
    reports: ["seller", "reports"] as const,
    notifications: ["seller", "notifications"] as const,
    storefront: ["seller", "storefront"] as const,
    ledger: ["seller", "ledger"] as const,
    settings: ["seller", "settings"] as const,
    shippingZones: ["seller", "shipping-zones"] as const,
  },
};
